---
abstract: 'type constraints and coercions for read-only data structures and locked hashes'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::Fatal: 0
  Test::More: 0.96
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.013, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Types-ReadOnly
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Type::Coercion::Wrapped:
    file: lib/Type/Coercion/Wrapped.pm
    version: 0.002
  Type::Tiny::Wrapped:
    file: lib/Type/Tiny/Wrapped.pm
    version: 0.002
  Type::Tiny::Wrapper:
    file: lib/Type/Tiny/Wrapper.pm
    version: 0.002
  Types::ReadOnly:
    file: lib/Types/ReadOnly.pm
    version: 0.002
requires:
  Type::Tiny: 0.022
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Types-ReadOnly/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Types-ReadOnly
  homepage: https://metacpan.org/release/Types-ReadOnly
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-types-readonly
version: 0.002
